### ISSUE TITLE
Maybe Bug Build Mod Version 2023.2.4.2f

### ISSUE THREAD

**Issue by KANGKAW1150** [mchhui/MWF-SHINING#31]
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[05:51:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[05:51:01] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[05:51:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[05:51:01] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[05:51:01] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_311, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_311
[05:51:01] [main/INFO] [FML]: Searching C:\Users\inwbm\AppData\Roaming\.minecraft\mods for mods
[05:51:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:51:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[05:51:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:51:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:51:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:51:02] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[05:51:02] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[05:51:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:51:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[05:51:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[05:51:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[05:51:02] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[05:51:03] [Client thread/ERROR] [minecraft/ResourceIndex]: Can't find the resource index file: C:\Users\inwbm\AppData\Roaming\.minecraft\assets\indexes\legacy.json
[05:51:03] [Client thread/INFO] [minecraft/Minecraft]: Setting user: Kasim
[05:51:05] [Client thread/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[05:51:05] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[05:51:05] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_311, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 88793024 bytes (84 MB) / 264916992 bytes (252 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 537.42' Renderer: 'NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2'
[05:51:05] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2860 Initialized
[05:51:05] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[05:51:05] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[05:51:05] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[05:51:06] [Client thread/INFO] [FML]: Searching C:\Users\inwbm\AppData\Roaming\.minecraft\mods for mods
[05:51:06] [Client thread/WARN] [FML]: Mod mcgltf is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.12.2-Forge-2.0.3.0
[05:51:06] [Client thread/INFO] [FML]: Mod easyeffect is missing the required element 'name'. Substituting easyeffect
[05:51:06] [Client thread/WARN] [FML]: Mod easyeffect is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[05:51:06] [Client thread/INFO] [FML]: Mod modularmovements is missing the required element 'name'. Substituting modularmovements
[05:51:06] [Client thread/WARN] [FML]: Mod modularmovements is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[05:51:07] [Client thread/WARN] [FML]: Mod easyeffect is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0
[05:51:07] [Client thread/WARN] [FML]: Mod modularmovements is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0
[05:51:07] [Client thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, Radicalred-Pack4 - Copy
[05:51:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 11/12/23 5:51 AM
Description: Initializing game

java.lang.IllegalArgumentException: Multiple entries with same key: modularwarfare=FMLMod:modularwarfare{2023.2.4.2f} and modularwarfare=FMLMod:modularwarfare{2023.2.4.2f}. To index multiple values under a key, use Multimaps.index.
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:429)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:429)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_311, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 137306288 bytes (130 MB) / 305991680 bytes (291 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 11 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID               | Version              | Source                                  | Signature                                |
	|:----- |:---------------- |:-------------------- |:--------------------------------------- |:---------------------------------------- |
	|       | minecraft        | 1.12.2               | minecraft.jar                           | None                                     |
	|       | mcp              | 9.42                 | minecraft.jar                           | None                                     |
	|       | FML              | 8.0.99.99            | forge-1.12.2-14.23.5.2860.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | forge            | 14.23.5.2860         | forge-1.12.2-14.23.5.2860.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | mcgltf           | 1.12.2-Forge-2.0.3.0 | MCglTF-1.12.2-Forge-2.0.3.0.jar         | None                                     |
	|       | modularwarfare   | 2023.2.4.2f          | modularwarfare-shining-snapshot-dev.jar | None                                     |
	|       | easyeffect       | 1.0                  | modularwarfare-shining-snapshot-dev.jar | None                                     |
	|       | modularmovements | 1.0                  | modularwarfare-shining-snapshot-dev.jar | None                                     |
	|       | modularwarfare   | 2023.2.4.2f          | modularwarfare-shining-snapshot-dev.jar | None                                     |
	|       | easyeffect       | 1.0                  | modularwarfare-shining-snapshot-dev.jar | None                                     |
	|       | modularmovements | 1.0                  | modularwarfare-shining-snapshot-dev.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 537.42' Renderer: 'NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.42, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Radicalred-Pack4 - Copy
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
[05:51:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\inwbm\AppData\Roaming\.minecraft\crash-reports\crash-2023-11-12_05.51.07-client.txt

Mods in Folder
- MCglTF-1.12.2-Forge-2.0.3.0
- modularwarfare-shining-snapshot-dev
- MWFPackager

**Comment by mchhui** [comment]
SRY,AS A MATTER OF FACT,NO CLUE :(
BUT
1.MWFPackager is not a lib for mwf(or mwf -shing),dont put it in mods.
2.-dev jar is not supported (protoxy did it and i dont know how it work),so dont use it.
